### ISSUE TITLE
Generated DKIM body hash is incorrect on some messages

### ISSUE THREAD

**Issue by tabascoterrier** [haraka/haraka-plugin-dkim#17]
### Describe the bug

In some circumstances, mails signed by the plugin have an invalid body hash value

### Expected behavior

Body hash should always be correct

### Observed behavior

This happens rarely, seemingly only on specific large sized mails. Capturing a real life failing mail was a challenge, so I ended up putting a simple fuzzer together to generate mails of different sizes until I could reliably trigger it, which is why the test case is full of nonsense.

If I diff the original and received mail there’s no change to the body, only the addition of the expected headers. So it doesn’t look like the body is getting mangled (which was my first thought), but instead it looks like the hash is miscalculated in some very specific scenario.

Size seems to be a factor, the smallest test case I’ve managed to generate is 1.7MB. Many larger files are fine, so maybe there's some kind of boundary condition I'm triggering?

### Steps To Reproduce

```python
# Sending the .eml file via swaks also triggers the issue, but swaks likes to 
# reformat the mail body which clouds things, so I've been using this python snippet
import smtplib

with open('test_case.eml') as f:
    msg = f.read()
    server = smtplib.SMTP('127.0.0.1', 25)
    server.login('foo', 'bar')
    server.sendmail('test@example.com', 'test@sometestdomain.co.uk', msg)
    server.quit()
```

DKIM verify the received email:

```bash
/opt/haraka-test/node_modules/haraka-plugin-dkim/bin/dkimverify --debug < /root/received.eml
Found 1 DKIM signatures
@example.com: DKIM fields validated OK
@example.com: a=rsa-sha256 c=relaxed/simple h=from,subject,message-id,to,mime-version
@example.com: bodyhash=QorqNMzdzWSw4UPFZEDAjr/31QYgeXbuZjGENTqTgWk= computed=Z5E8nAMMpAwvDnle/JGaZmkDkp3NDPjC1zoGkwslahk=
{"identity":"@example.com","selector":"jun2025","domain":"example.com","result":"fail"}
identity="@example.com" domain="example.com" result=fail (body hash did not verify)
```

[test_case.eml.zip](https://github.com/user-attachments/files/20867094/test_case.eml.zip)

```
diff test_case.eml received.eml
0a1,7
> Received: (Haraka outbound); Mon, 23 Jun 2025 13:52:46 +0000
> Authentication-Results: haraka-scratch;
> 	auth=pass (cram-md5)
> Received: from haraka-scratch.lxd (Unknown [127.0.0.1])
> 	by haraka-scratch (Haraka/3.1.1) with ESMTPA id 9567DA7E-AA3F-4A10-802F-94D302BCAD67.1
> 	envelope-from <test@example.com> (authenticated bits=0);
> 	Mon, 23 Jun 2025 13:52:46 +0000
6a14,26
> DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple;
> 	d=example.com; s=jun2025;
> 	h=from:subject:message-id:to:mime-version;
> 	bh=QorqNMzdzWSw4UPFZEDAjr/31QYgeXbuZjGENTqTgWk=;
> 	b=CbAuYB+KJvVLmyUZcYcbg832sXzXzXziiuRK029yM5iB1Uv+3tTtkW+fCSNx1BSSU7Tv0kJQEI
> 	f+ZAm+BETIZ0XWlYXQNTmIEu1g4DXeHhlBtUyDTzX9at+ml02LOPIBVmhsDruhEgWWwYGMNHeY3s
> 	CWwz7GDRUVwyaG7GtiZ+FyEeNjJF93dvu4yNMSUc/6vs6LBgUIS36UiUIuv1Xbu1DPbEFvEgnGL6
> 	AaHTkMBKVirgliFTC7uufNET/jsdaWz9ZblQfsWZfQd7Rvu+/z5N182Vq3yKSpchQiR5SsIHtct4
> 	S5D3ZsHUja1wFLiCSV6PjQS17d9eRUkvrfzvwY3g==
> Date: Mon, 23 Jun 2025 13:52:46 +0000
> X-Peer: ('10.1.2.100', 53910)
> X-MailFrom: test@example.com
> X-RcptTo: test@sometestdomain.co.uk
```

```ini
# plugins
tls
auth/flat_file
dkim
```

```ini
# dkim.ini
[main]

[sign]
enabled = true
headers = From, Sender, Reply-To, Subject, Date, Message-ID, To, Cc, MIME-Version

[verify]
enabled = true
```

### System Info

Haraka | Haraka.js — Version: 3.1.1
 --- | :---
Node | v22.16.0
OS | Linux haraka-scratch 5.15.0-117-generic #127-Ubuntu SMP Mon Jul 8 13:10:05 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
openssl | OpenSSL 3.0.13 30 Jan 2024 (Library: OpenSSL 3.0.13 30 Jan 2024)

### Additional context

This is a fresh build, with just haraka-plugin-dkim added. Let me know if there's any more info that would be helpful.

**Comment by tabascoterrier** [comment]
Some more insight. I wanted a test case I could plug unmodified into the plugin test suite, as the previous one had LF endings which I was just relying on the sending SMTP library to sort out. This new test case uses CRLF consistently.

If I run this new test case through the plugin test suite, it calculates the correct hash. However if I send it via Haraka, the wrong hash is calculated. So it doesn’t look like a bug in the dkim plugin as such, but something is happening to the body elsewhere in Haraka.

[test_case.eml.zip](https://github.com/user-attachments/files/20943444/test_case.eml.zip)

```js
// Passes
it('body hash bug: test_case.eml', async () => {
    const fs = require('fs/promises');
    const path = require('path');
    const emlPath = path.resolve(__dirname, 'test_case.eml');
    const email = await fs.readFile(emlPath, 'utf8');
    const header = new message.Header()

    const signer = new DKIMSignStream(props, header, (n, dkim) => {
      assert.equal(
        getValueFromDKIM(dkim, 'bh'),
        'tJjICZA4QDCXd5rdeKHX6LkWZrGps0LQq0YvCw5byxI=',
      )
    })
    signer.write(Buffer.from(email))
    signer.end()
  });
```

```bash
root@haraka-scratch:~# /opt/haraka-test/node_modules/haraka-plugin-dkim/bin/dkimverify --debug < /root/test_case.received.eml
Found 1 DKIM signatures
@example.com: DKIM fields validated OK
@example.com: a=rsa-sha256 c=relaxed/simple h=from,subject,message-id,to,mime-version
@example.com: bodyhash=GUGumP17ZHPF9DPauOv4+heltNnIpkWu/vJuUMedL6E= computed=tJjICZA4QDCXd5rdeKHX6LkWZrGps0LQq0YvCw5byxI=
{"identity":"@example.com","selector":"jun2025","domain":"example.com","result":"fail"}
identity="@example.com" domain="example.com" result=fail (body hash did not verify)
```

I’ll continue to dig.

**Comment by tabascoterrier** [comment]
Ok, I think this might actually be a dot stuffing bug; if I dump the data received as it hits the dkim plugin, and diff it to the original test case, I see

```diff
root@haraka-scratch:~# diff test_case.eml haraka-dkim-sign-1751020767718.eml
0a1,6
> Authentication-Results: haraka-scratch;
> 	auth=pass (cram-md5)
> Received: from haraka-scratch.lxd (Unknown [127.0.0.1])
> 	by haraka-scratch (Haraka/3.1.1) with ESMTPA id 8DC6164F-149B-455F-9739-D2871C598F52.1
> 	envelope-from <test@example.com> (authenticated bits=0);
> 	Fri, 27 Jun 2025 10:39:27 +0000
32979c32985
< .=E1FqF54=FD`v/*)L=E2/'A=FAD=3Dgi`P"=3DkhCM_f=F3`-n=E4=F636*Mce23 O]k0q?;G-=
---
> ..=E1FqF54=FD`v/*)L=E2/'A=FAD=3Dgi`P"=3DkhCM_f=F3`-n=E4=F636*Mce23 O]k0q?;G-=
```

If I compare the original email to the queue file, that line originally started with a single period, and was dot stuffed to a double period. But somehow that one line was not unstuffed correctly, when all the others were.

So I think this might be a bug in message-stream. 

~~Possibly where two periods fall either side of a buffer chunk, e.g. one call to `process_buf(chunk)` ends with the first period, and the next call to `process_buf(chunk)` starts with the second period, and thus the "Remove dot-stuffing" code never fires.~~ That might be premature of me, I might be misunderstanding how buffers work in message-stream.

**Comment by msimerson** [comment]
So... dot stuffing in message stream is disabled by default. In Haraka transaction.js, dot stuffing is enabled by default. That could be the mismatch. What happens if you edit haraka-plugin-dkim/index.js as follows:

```js
diff --git a/index.js b/index.js
index 96eabde..1351ba3 100644
--- a/index.js
+++ b/index.js
@@ -101,6 +101,7 @@ exports.hook_pre_send_trans_email = function (next, connection) {
         connection.transaction.notes.dkim_signed = true
         next()
       }),
+      { dot_stuffing: true }
     )
   })
 }
```

**Comment by msimerson** [comment]
In message-stream/index.js, this is an interesting bit of code:

```js
      // Remove dot-stuffing if required
      if (
        !this.dot_stuffing &&
        line.length >= 4 &&
        line[0] === 0x2e &&
        line[1] === 0x2e
      ) {
        line = line.slice(1)
      }
```

So, it fires when `!dot_stuffing`, or better written, when `this.dot_stuffing === false`. That's not very intuitive.

So it seems that dot stuffing in message stream **is** enabled by default, because the default value is false.

**Comment by tabascoterrier** [comment]
I appreciate you having a look at this Matt :)

I've tried adding `dot_stuffing: true` to haraka-plugin-dkim/index.js, but no change sadly.

The test case contains a number of lines that begin with a dot, and if I capture the enqueued file from the queue directory I can see that all those lines are stuffed with a second dot, so it does look like the dot stuffing is being added correctly.

If I dump the data received at the beginning of the dkim plugin all the dot stuffing has been removed again... aside from that one line which retains an extraneous leading dot.

About the only reason I could think of that the "Remove dot-stuffing if required" code wasn't operating on that one line was that the line wasn't being passed into `process_buf` in one piece, but I'll freely admit that I'm out of my depth at this point!

**Comment by msimerson** [comment]
> on that one line was that the line wasn't being passed into process_buf in one piece

Actually, I think you're right in the correct depth. Toss a couple lines of code in there to log the lines and their length, and test your theory. That dog might hunt!

**Comment by tabascoterrier** [comment]
I have actually been trying to knock up a test case in message-stream (I was hoping to generate a nice small human readable file with periods either side of that buffer boundary), but I've been having strange issues. But it's late on a Friday night so I'm sure having a fresh look on Monday will help.

The scratch file below just adds data from a file into a message stream and logs the output it to the console:

```js
// scratch file
const fs = require('fs')
const path = require('path')
const MessageStream = require('../index')
const testFile = path.join(__dirname, 'scratch_test.txt');

ms = new MessageStream({ main: {} }, 'msg', [])

fs.readFileSync(testFile, 'utf-8').split(/\r\n/).forEach((line) => {
    ms.add_line(line + '\r\n');
})

ms.add_line_end();

ms.get_data((data) => {
    console.log(data.toString())
})
```

The test data is

```
... many lines
Line 0814 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Line 0815 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Line 0816 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Line 0817 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Line 0818 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Line 0819 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

but weirdly the console log output is missing some bytes around the 64k mark:
```
Line 0814 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Line 0815 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Line 0816 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Line 0818 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Line 0819 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Line 0820 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

I was stepping through with a debugger and it happens around line 476 in message-stream/index.js, when `input.length + this.bufs_size > this.buffer_size` goes over 64k. But message-stream can't be dropping a chunk of bytes every 64k else all large emails would be broken, so it's likely user error on my part. I'll have another crack at understanding all this buffer magic next week! edit - yes, it's important to pass an array of headers into the MessageStream constructor, else it stays in it's header parsing mode and the body goes squirrelly.

**Comment by msimerson** [comment]
The comment from BillM on this thread is interesting, and maybe relevant. https://stackoverflow.com/questions/15224224/smtp-dot-stuffing-when-and-where-to-do-it

**Comment by tabascoterrier** [comment]
Thanks Matt. I think I've (finally) found the culprit; in message stream there's:

```js
process_buf(buf) {
  while ((offset = indexOfLF(buf)) !== -1) {
    ...
    // remove dot stuffing
    this.read_ce.fill(line)

  } // end of while loop

  // Check for data left in the buffer
  if (buf.length > 0 && this.headers_found_eoh) {
    this.read_ce.fill(buf) // without any dot stuffing removal
  }
}
```

As I understand it, that while loop is plucking complete lines (strings ending in an LF) from `buf`, stripping dots and feeding them into `this.read_ce.fill(line)`

After, if there's anything left over in `buf`, that gets fed into `this.read_ce.fill(buf)` (with no dot stuffing removal)

I started dumping those 'leftovers' in that last block to a file and lo, I see my problematic dot stuffed line.

What I think is happening is occasionally a line gets split by an earlier buffer boundary, so the end of `buf` contains the line starting with stuffed dot, but no LF, and so dot stuffing removal doesn't get triggered (If I change `this.buffer_size` in ChunkEmitter my test case gets the correct hash again)

So presumably the fix would be to break the dot-stuffing removal out into a separate function, and call it both in the while loop and in the final "Check for data left in the buffer" block. I'll spend some more time checking things out, and then do an issue and PR over in message-stream.

**Comment by msimerson** [comment]
Great sleuthing! Please see if haraka/message-stream#9 does the needful for you.

**Comment by tabascoterrier** [comment]
Thanks, it took a while 😄

Thanks also for the fix, although it doesn't look like dot-stuffing is being removed for any lines now - presumably the new `remove_dot_stuffing()` isn't updating by reference and needs a return value ?

**Comment by msimerson** [comment]
> presumably the new remove_dot_stuffing() isn't updating by reference

Oh right, primitives are passed by value but arrays and objects are passed by reference. Doh! I'll fix that...

**Comment by msimerson** [comment]
Fixed. And I added a few tests, which you're welcome to extend with the test cases you've sleuthed.

**Comment by tabascoterrier** [comment]
Thanks Matt. 

With the new `dot_stuffed` changes, things get a little odd. My test case email reaches the DKIM plugin in the correct state, the right hash is calculated and added as expected. But somewhere later in the process, the message body gets mangled - any line that originally began with a single dot ends up with that dot removed in the final received message.

If I use the new `remove_dot_stuffing()` function but revert to the old `dot_stuffing` boolean logic, everything works perfectly. All my end-to-end tests pass, it looks solid. So maybe something else in the stack is assuming the old `dot_stuffing: false` behaviour, and flipping that default is causing an issue?

**Comment by msimerson** [comment]
Look in Haraka/smtp_client at line 215 and see if changing it to this fixes it for you:

```diff
    start_data (data) {
        this.response = [];
        this.command = 'dot';
        // SUNSET: dot_stuffing was renamed to dot_stuffed, remove it after 2026-01
        data.pipe(this.socket, { dot_stuffed: false, dot_stuffing: true, ending_dot: true, end: false });
    }
```

**Comment by tabascoterrier** [comment]
Hmm, still the same issue I'm afraid.

I'll see if I can put some nice portable end-to-end CI tests together for this, perhaps using dagger.io. That might make things easier.

**Comment by msimerson** [comment]
Is the next hop delivered by outbound? If so, apply the change to outbound/index.js in haraka/Haraka#3473 and see if that makes the difference.

**Comment by tabascoterrier** [comment]
Thanks Matt, yes, outbound is next up, although I get an exception after making those outbound/index.js changes:

```
[INFO] [-] [outbound] Transaction delivery for domain: sometestdomain.co.uk
[CRIT] [-] [core] TypeError: Cannot read properties of undefined (reading 'length')
[CRIT] [-] [core]     at ChunkEmitter.fill (/root/.nvm/versions/node/v22.16.0/lib/node_modules/Haraka/node_modules/haraka-message-stream/index.js:476:31)
[CRIT] [-] [core]     at MessageStream.process_buf (/root/.nvm/versions/node/v22.16.0/lib/node_modules/Haraka/node_modules/haraka-message-stream/index.js:304:20)
[CRIT] [-] [core]     at MessageStream._read (/root/.nvm/versions/node/v22.16.0/lib/node_modules/Haraka/node_modules/haraka-message-stream/index.js:244:16)
[CRIT] [-] [core]     at Immediate.<anonymous> (/root/.nvm/versions/node/v22.16.0/lib/node_modules/Haraka/node_modules/haraka-message-stream/index.js:236:49)
[CRIT] [-] [core]     at process.processImmediate (node:internal/timers:485:21)
[NOTICE] [-] [core] Shutting down
[NOTICE] [-] [server] worker 1 exited with error code: 1
[NOTICE] [-] [server] worker started worker=2 pid=21265
```

**Comment by msimerson** [comment]
Try: revert the first change and make only the second change in the pipe command.

**Comment by msimerson** [comment]
Ahah, I found the problem:

```diff
diff --git a/index.js b/index.js
index 478fc70..e84e78d 100644
--- a/index.js
+++ b/index.js
@@ -262,7 +262,7 @@ class MessageStream extends Stream {
   }
 
   remove_dot_stuffing(buf) {
-    if (!this.dot_stuffed) return
+    if (!this.dot_stuffed) return buf
 
     if (buf.length >= 4 && buf[0] === 0x2e && buf[1] === 0x2e) {
       return buf.slice(1)
```

I missed updating one of the returns.

**Comment by msimerson** [comment]
Hmmm, a test should be added in message-stream to verify that when `{ dot_stuffed: false }` is passed, the line(s) are returned unaltered.

**Comment by tabascoterrier** [comment]
Ahh, easily missed. Brilliant, that seems to have fixed everything, all looks good here now.

The changes to outbound/index.js are the key. I've tested those both with and without the changes to smtp_client.js and both cases work fine for me.
